project:
  type: website
  output-dir: docs

website:
  title: "Modul 08-006-0007"
  search: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Grundlagen"
        menu:
          - text: "1. Einleitung"
            href: "1 Einleitung, Vorstellung der Fallbeispiele, Gruppenfindung/Praesentation1_Einleitung.qmd"
          - text: "2. Messung & Definition"
            href: "2_messung/praesentation2_messung.qmd"
      #     - text: "3. Psychometrie"
      #       href: "3 Psychometrische Fragebögen und Konstrukte/Praesentation3_Frageboegen.qmd"
      # - text: "Spezielle Anwendungsfälle"
      #   menu:
      #     - text: "4. Kultursensible Interventionen"
      #       href: "4_kultursensibel/praesentation4_kultur.qmd"
      #     - text: "5. Webbasierte Interventionen"
      #       href: "5_webbasiert/praesentation5_web.qmd"
      # - text: "Intervention Mapping"
      #   menu:
      #     - text: "7. Bedarfsanalyse"
      #       href: "7 Intervention Mapping I - Bedarfsanalyse und logisches Modell des Problems/Praesentation7_Bedarfsanalyse.qmd"
      #     - text: "8. Zielsetzung"
      #       href: "8 Intervention Mapping II - Zielsetzung und Modell der Veränderung/Praesentation8_Zielsetzung.qmd"
      #     - text: "9. Methodenwahl"
      #       href: "9 Intervention Mapping III - Auswahl von Methoden und Praktischen Anwendungen/Praesentation9_Methoden.qmd"
      #     - text: "10. Materialentwicklung"
      #       href: "10 Intervention Mapping IV - Materialentwicklung/Praesentation10_Materialentwicklung"
      #     - text: "11. Annahme & Umsetzung"
      #       href: "11 Intervention Mapping V - Annahme und Umsetzung/Praesentation11_Annahme.qmd"
      #     - text: "12. Evaluation"
      #       href: "12 Intervention Mapping VI - Evaluation und Dokumentation/Praesentation12_Eval.qmd"
      - text: "Ressourcen zum Lernen"
        menu:
          - text: "Stichwortliste"
            href: "Stichwortliste.qmd"
          - text: "Linksammlung"
            href: "Linksammlung.qmd"
format:
  revealjs:
    css: styles.css          # Path relative to the project root
    logo: leipzig_logo.svg
    include-in-header:
      - text: |
          <style>
          .reveal .slide-logo {
            max-height: unset;
            height: 150px;
          }
          </style>
    theme: simple
    transition: slide
    chalkboard: true
    touch: true
    controls: true
    incremental: true
    slide-number: true
  docx:
    reference-doc: template.docx
  html:
    theme: darkly

bibliography: bibliography.bib
csl: apa.csl