---
title: "Präsentationsfolien und online-Termine"
format: html
editor: visual
---

Willkommen auf der Kursseite. Hier findet ihr alle Präsentationen und Materialien für das Sommersemester 2026.

## Kursinhalte

### Grundlagen

1.  [Einleitung & Fallbeispiele](1%20Einleitung,%20Vorstellung%20der%20Fallbeispiele,%20Gruppenfindung/Praesentation1_Einleitung.qmd)
2.  [Messung und Definition sportlicher Aktivität](2_messung/praesentation2_messung.qmd)
    - [Steckbrief](2_messung/steckbrief.qmd)
    
3.  [Psychometrische Fragebögen](3%20Psychometrische%20Fragebögen%20und%20Konstrukte/Praesentation3_Frageboegen.qmd)
    - [Steckbrief Konstrukte](3%20Psychometrische%20Fragebögen%20und%20Konstrukte/Steckbrief%20Konstrukt.qmd)

4.  [Kultursensible Interventionen](4_kultursensibel/praesentation4_kultur.qmd)
5.  [Webbasierte Interventionen](5_webbasiert/praesentation5_web.qmd)
    

### Methoden & Design

6.  [Studiendesign & Stichprobe](6%20Studiendesign%20und%20Stichprobe/Praesentation6_Studiendesign.qmd)
    - [R Skript Poweranalyse](6%20Studiendesign%20und%20Stichprobe/R-Skript_Poweranalyse.R)
    - [Arbeitsblätter](6%20Studiendesign%20und%20Stichprobe/Arbeitsblätter.qmd)   
    
### Intervention Mapping (IM)

7.  [IM I: Bedarfsanalyse](7%20Intervention%20Mapping%20I%20-%20Bedarfsanalyse%20und%20logisches%20Modell%20des%20Problems/Praesentation7_Bedarfsanalyse.qmd)
    - [Arbeitsblatt](7%20Intervention%20Mapping%20I%20-%20Bedarfsanalyse%20und%20logisches%20Modell%20des%20Problems/Arbeitsblatt%20Bedarfsanalyse.qmd)
    - [Logisches Modell des Problems - Vorlage für draw.io (Rechtsklick-Ziel speichern unter ...)](7%20Intervention%20Mapping%20I%20-%20Bedarfsanalyse%20und%20logisches%20Modell%20des%20Problems/logisches_modell_problem_leer.drawio)
    
8.  [IM II: Zielsetzung](8%20Intervention%20Mapping%20II%20-%20Zielsetzung%20und%20Modell%20der%20Veränderung/Praesentation8_Zielsetzung.qmd)
    - [Arbeitsblatt](8%20Intervention%20Mapping%20II%20-%20Zielsetzung%20und%20Modell%20der%20Veränderung/Arbeitsblatt_Zielsetzung.qmd)
    - [Logisches Modell der Veränderung - Vorlage für draw.io (Rechtsklick-Ziel speichern unter ...)](8%20Intervention%20Mapping%20II%20-%20Zielsetzung%20und%20Modell%20der%20Veränderung/logisches_modell_veraenderung_leer.drawio)
    
9.  [IM III: Methodenwahl](9%20Intervention%20Mapping%20III%20-%20Auswahl%20von%20Methoden%20und%20Praktischen%20Anwendungen/Praesentation9_Methoden.qmd)
    - [Arbeitsblatt](9%20Intervention%20Mapping%20III%20-%20Auswahl%20von%20Methoden%20und%20Praktischen%20Anwendungen/Arbeitsblatt_Methoden.qmd)
10. [IM IV: Materialentwicklung](10%20Intervention%20Mapping%20IV%20-%20Materialentwicklung/Praesentation10_Materialentwicklung.qmd)
    - [Arbeitsblatt](10%20Intervention%20Mapping%20IV%20-%20Materialentwicklung/Arbeitsblatt_Material.qmd)
    - [Logisches Modell der Intervention - Vorlage für draw.io (Rechtsklick-Ziel speichern unter ...)](10%20Intervention%20Mapping%20IV%20-%20Materialentwicklung/logisches_modell_leer.drawio)


<!-- 11. [IM V: Umsetzung](11%20Intervention%20Mapping%20V%20-%20Annahme%20und%20Umsetzung/Praesentation11_Annahme.qmd) -->
<!-- 12. [IM VI: Evaluation](12%20Intervention%20Mapping%20VI%20-%20Evaluation%20und%20Dokumentation/Praesentation12_Eval.qmd) -->

### Ressourcen

- [Stichwortliste](Stichwortliste.qmd)

- [Quizlet-Kurs](https://quizlet.com/class/32543111/materials)

- [Linksammlung (weiterführende Videos und Beispiele von Interventionen, optional)](Linksammlung.qmd)

<!-- ### Abschluss & Rahmenbedingungen -->

<!-- 13. [Forschungsethik](13%20Forschungsethik%20und%20Datenschutz/Praesentation13_Ethik.qmd) -->
<!-- 14. [Lehrproben & Hausarbeit](14%20verbleibende%20Lehrproben,%20Kriterien%20der%20Hausarbeit,%20Peer-Feedback/Praesentation14_Abschluss_APA.qmd) -->

------------------------------------------------------------------------

### Hinweise zur Nutzung

-    Taste `m`, um das Menü aufzurufen (Hier ist der Druck als PDF möglich), oder `f` für den Vollbildmodus.
-   Für externe Links wird keine Haftung übernommen. 

### Seminartermine

Jeweils Montag

13.04.26

20.04.26

27.04.26

04.05.26

11.05.26

18.05.26

01.06.26

08.06.26

15.06.26

22.06.26

29.06.26

06.07.26

